name: home-library-service

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: unless-stopped
    user: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - public-network
    command: >
      postgres
      -c logging_collector=on
      -c log_directory='/var/log/postgresql'
      -c log_filename='postgresql.log'
      -c log_statement='all'
      -c log_min_duration_statement=0
      -c log_rotation_age='1d'
      -c log_rotation_size='10MB'
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 1s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        PORT: ${PORT}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/home-library-service
    ports:
      - "${PORT}:${PORT}"
    networks:
      - public-network
    command: npm run start:docker
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/dist
    depends_on:
      db:
        condition: service_healthy

networks:
  public-network:
    driver: bridge

volumes:
  db_data:
  db_logs:
